### ISSUE TITLE
Does not respect gnome dpi settings for scrollbars

### ISSUE THREAD

**Issue by johalun** [kiwanami/emacs-window-layout#12]
Hi 
I opened an issue here
#https://github.com/kiwanami/emacs-window-manager/issues/88
but I think maybe the bug is in this repo. 

The simple test below shows that the scrollbar is place too far to the right, in the middle of the right side column. 

```
(setq ss
      (wlf:layout
       '(| (:left-max-size 20)
		   folder 
		   (- (:lower-size-ratio 0.6)
			  summary message))
       '((:name folder :buffer "*scratch*")
         (:name summary :buffer "*Messages*"))))
```

**Comment by johalun** [comment]
I discovered that the bug is related to this setting:
gsettings set org.gnome.desktop.interface scaling-factor [1,2]
For scaling factor 1 it works as expected, for scaling factor 2 the scrollbars are places at 2*x-position.

**Comment by johalun** [comment]
Seem to be emacs/gtk3 scrollbar problem.

**Comment by kiwanami** [comment]
Thank you for your information about a trouble of combination with HiDPI and GTK3.
It's useful for the people who use large HiDPI displays.
